### ISSUE TITLE
The marker positions in the trackable's frame of reference

### ISSUE THREAD

**Issue by Monopolymer** [uzh-rpg/rpg_monocular_pose_estimator#10]
Hello I would like to build my own marker to test the pose estimator with live cameras. Say i mount the led's on a board would the center of the board be (0,0,0)? so that the position in the marker_position.yaml is calculatet from the center?

**Comment by eliasm** [comment]
Yes. You have to define the LED positions with respect to an arbitrary reference frame. The pose estimator will output the pose with respect to that frame.
