### ISSUE TITLE
Recommended Camera

### ISSUE THREAD

**Issue by Pedro-Roque** [uzh-rpg/rpg_monocular_pose_estimator#4]
Good afternoon,

I would like to know which cameras and, specially, IR Filters (and where to get them) do you advise to use with IR led's and filters. I've tried the following approach:
- Logitech C270 getting RGB LED's, without much success (even with low noise on the image I couldn't get an estimated pose);
- Thought of Pixy with IR-Lock setup, but I am not sure if it can detect LED's up to 5m distant from the sensor and 30cm distant from each-other;

What camera and filter do you use in your setup, and what distance can you get? I am going to use this on a Quadrotor.

With my best regards,

Pedro Roque

**Comment by eliasm** [comment]
Hi Pedro,

You can find all details about the hardware we used and the achieved distances in the following publication: http://rpg.ifi.uzh.ch/docs/ICRA14_Faessler.pdf

Best,
Elias

**Comment by kubark42** [comment]
I'd vote for reopening this. Although the original authors are busy with other tasks, the wider community could find a discussion on (un)successful sensors and techniques useful.

FWIW, we haven't had much success with the pose estimator using a Point Grey Grasshopper 3.0, which is basically a USB 3.0 wrapper around the Sony IMX174 sensor.[*] On paper, the Sony sensor outperforms the MatrixVision mvBlueFOXMLC200w used in the original ICRA article.

[*]Admittedly, we didn't dig deep down into the failure.

**Comment by Pedro-Roque** [comment]
@kubark42 That's precisely what I meant with this topic!

I am planning on getting a BlueFOX with a Daylight cut filter ( @eliasm , that's the same filter as yours? You don't specify that ).

Also, is there anyway to modify the package in order to get some middle-steps image?

Thanks in advance!

**Comment by eliasm** [comment]
Yes, in the paper we were using the BlueFOX with a daylight-cut filter. A more precise filter that fits the LEDs' wavelength will probably further improve the performance. 

It shouldn't be too hard to save intermediate steps by adjusting the LED detector method: https://github.com/uzh-rpg/rpg_monocular_pose_estimator/blob/master/monocular_pose_estimator_lib/src/led_detector.cpp#L35

**Comment by Pedro-Roque** [comment]
Ok, thank you very much @eliasm . I will let you know if I got news !
